/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_BARRIER_INIT = PMPI_BARRIER_INIT
#pragma weak mpi_barrier_init__ = PMPI_BARRIER_INIT
#pragma weak mpi_barrier_init_ = PMPI_BARRIER_INIT
#pragma weak mpi_barrier_init = PMPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_BARRIER_INIT = pmpi_barrier_init__
#pragma weak mpi_barrier_init__ = pmpi_barrier_init__
#pragma weak mpi_barrier_init_ = pmpi_barrier_init__
#pragma weak mpi_barrier_init = pmpi_barrier_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_BARRIER_INIT = pmpi_barrier_init_
#pragma weak mpi_barrier_init__ = pmpi_barrier_init_
#pragma weak mpi_barrier_init_ = pmpi_barrier_init_
#pragma weak mpi_barrier_init = pmpi_barrier_init_
#else
#pragma weak MPI_BARRIER_INIT = pmpi_barrier_init
#pragma weak mpi_barrier_init__ = pmpi_barrier_init
#pragma weak mpi_barrier_init_ = pmpi_barrier_init
#pragma weak mpi_barrier_init = pmpi_barrier_init
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_BARRIER_INIT = PMPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_barrier_init__ = pmpi_barrier_init__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_barrier_init = pmpi_barrier_init
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_barrier_init_ = pmpi_barrier_init_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_BARRIER_INIT  MPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_barrier_init__  mpi_barrier_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_barrier_init  mpi_barrier_init
#else
#pragma _HP_SECONDARY_DEF pmpi_barrier_init_  mpi_barrier_init_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_BARRIER_INIT as PMPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_barrier_init__ as pmpi_barrier_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_barrier_init as pmpi_barrier_init
#else
#pragma _CRI duplicate mpi_barrier_init_ as pmpi_barrier_init_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_barrier_init__ = MPI_BARRIER_INIT
#pragma weak mpi_barrier_init_ = MPI_BARRIER_INIT
#pragma weak mpi_barrier_init = MPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_BARRIER_INIT = mpi_barrier_init__
#pragma weak mpi_barrier_init_ = mpi_barrier_init__
#pragma weak mpi_barrier_init = mpi_barrier_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_BARRIER_INIT = mpi_barrier_init_
#pragma weak mpi_barrier_init__ = mpi_barrier_init_
#pragma weak mpi_barrier_init = mpi_barrier_init_
#else
#pragma weak MPI_BARRIER_INIT = mpi_barrier_init
#pragma weak mpi_barrier_init__ = mpi_barrier_init
#pragma weak mpi_barrier_init_ = mpi_barrier_init
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_BARRIER_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_barrier_init__ = PMPI_BARRIER_INIT
#pragma weak pmpi_barrier_init_ = PMPI_BARRIER_INIT
#pragma weak pmpi_barrier_init = PMPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_BARRIER_INIT = pmpi_barrier_init__
#pragma weak pmpi_barrier_init_ = pmpi_barrier_init__
#pragma weak pmpi_barrier_init = pmpi_barrier_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_BARRIER_INIT = pmpi_barrier_init_
#pragma weak pmpi_barrier_init__ = pmpi_barrier_init_
#pragma weak pmpi_barrier_init = pmpi_barrier_init_
#else
#pragma weak PMPI_BARRIER_INIT = pmpi_barrier_init
#pragma weak pmpi_barrier_init__ = pmpi_barrier_init
#pragma weak pmpi_barrier_init_ = pmpi_barrier_init
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_BARRIER_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_BARRIER_INIT( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_barrier_init_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_barrier_init")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_barrier_init_ PMPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_barrier_init_ pmpi_barrier_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_barrier_init_ pmpi_barrier_init
#else
#define mpi_barrier_init_ pmpi_barrier_init_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Barrier_init
#define MPI_Barrier_init PMPI_Barrier_init
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_barrier_init_ MPI_BARRIER_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_barrier_init_ mpi_barrier_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_barrier_init_ mpi_barrier_init
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_barrier_init_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *ierr ){
    *ierr = MPI_Barrier_init( (MPI_Comm)(*v1), (MPI_Info)(*v2), (MPI_Request *)(v3) );
}
