/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_COMM_CREATE_FROM_GROUP = PMPI_COMM_CREATE_FROM_GROUP
#pragma weak mpi_comm_create_from_group__ = PMPI_COMM_CREATE_FROM_GROUP
#pragma weak mpi_comm_create_from_group_ = PMPI_COMM_CREATE_FROM_GROUP
#pragma weak mpi_comm_create_from_group = PMPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group__
#pragma weak mpi_comm_create_from_group__ = pmpi_comm_create_from_group__
#pragma weak mpi_comm_create_from_group_ = pmpi_comm_create_from_group__
#pragma weak mpi_comm_create_from_group = pmpi_comm_create_from_group__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group_
#pragma weak mpi_comm_create_from_group__ = pmpi_comm_create_from_group_
#pragma weak mpi_comm_create_from_group_ = pmpi_comm_create_from_group_
#pragma weak mpi_comm_create_from_group = pmpi_comm_create_from_group_
#else
#pragma weak MPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group
#pragma weak mpi_comm_create_from_group__ = pmpi_comm_create_from_group
#pragma weak mpi_comm_create_from_group_ = pmpi_comm_create_from_group
#pragma weak mpi_comm_create_from_group = pmpi_comm_create_from_group
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak MPI_COMM_CREATE_FROM_GROUP = PMPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_comm_create_from_group__ = pmpi_comm_create_from_group__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_comm_create_from_group = pmpi_comm_create_from_group
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_comm_create_from_group_ = pmpi_comm_create_from_group_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_COMM_CREATE_FROM_GROUP  MPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_comm_create_from_group__  mpi_comm_create_from_group__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_comm_create_from_group  mpi_comm_create_from_group
#else
#pragma _HP_SECONDARY_DEF pmpi_comm_create_from_group_  mpi_comm_create_from_group_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_COMM_CREATE_FROM_GROUP as PMPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_comm_create_from_group__ as pmpi_comm_create_from_group__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_comm_create_from_group as pmpi_comm_create_from_group
#else
#pragma _CRI duplicate mpi_comm_create_from_group_ as pmpi_comm_create_from_group_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_comm_create_from_group__ = MPI_COMM_CREATE_FROM_GROUP
#pragma weak mpi_comm_create_from_group_ = MPI_COMM_CREATE_FROM_GROUP
#pragma weak mpi_comm_create_from_group = MPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_COMM_CREATE_FROM_GROUP = mpi_comm_create_from_group__
#pragma weak mpi_comm_create_from_group_ = mpi_comm_create_from_group__
#pragma weak mpi_comm_create_from_group = mpi_comm_create_from_group__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_COMM_CREATE_FROM_GROUP = mpi_comm_create_from_group_
#pragma weak mpi_comm_create_from_group__ = mpi_comm_create_from_group_
#pragma weak mpi_comm_create_from_group = mpi_comm_create_from_group_
#else
#pragma weak MPI_COMM_CREATE_FROM_GROUP = mpi_comm_create_from_group
#pragma weak mpi_comm_create_from_group__ = mpi_comm_create_from_group
#pragma weak mpi_comm_create_from_group_ = mpi_comm_create_from_group
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_COMM_CREATE_FROM_GROUP")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_comm_create_from_group__ = PMPI_COMM_CREATE_FROM_GROUP
#pragma weak pmpi_comm_create_from_group_ = PMPI_COMM_CREATE_FROM_GROUP
#pragma weak pmpi_comm_create_from_group = PMPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group__
#pragma weak pmpi_comm_create_from_group_ = pmpi_comm_create_from_group__
#pragma weak pmpi_comm_create_from_group = pmpi_comm_create_from_group__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group_
#pragma weak pmpi_comm_create_from_group__ = pmpi_comm_create_from_group_
#pragma weak pmpi_comm_create_from_group = pmpi_comm_create_from_group_
#else
#pragma weak PMPI_COMM_CREATE_FROM_GROUP = pmpi_comm_create_from_group
#pragma weak pmpi_comm_create_from_group__ = pmpi_comm_create_from_group
#pragma weak pmpi_comm_create_from_group_ = pmpi_comm_create_from_group
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_COMM_CREATE_FROM_GROUP")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_COMM_CREATE_FROM_GROUP( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group__( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_comm_create_from_group_( MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_comm_create_from_group")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_comm_create_from_group_ PMPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_comm_create_from_group_ pmpi_comm_create_from_group__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_comm_create_from_group_ pmpi_comm_create_from_group
#else
#define mpi_comm_create_from_group_ pmpi_comm_create_from_group_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Comm_create_from_group
#define MPI_Comm_create_from_group PMPI_Comm_create_from_group
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_comm_create_from_group_ MPI_COMM_CREATE_FROM_GROUP
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_comm_create_from_group_ mpi_comm_create_from_group__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_comm_create_from_group_ mpi_comm_create_from_group
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_comm_create_from_group_ ( MPI_Fint *v1, char *v2 FORT_MIXED_LEN(d2), MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr FORT_END_LEN(d2) ){
    *ierr = MPI_Comm_create_from_group( (MPI_Group)*v1, v2, (MPI_Info)(*v3), (MPI_Errhandler)*v4, (MPI_Comm *)(v5) );
}
