/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_DELETE_ERROR_CLASS = PMPIX_DELETE_ERROR_CLASS
#pragma weak mpix_delete_error_class__ = PMPIX_DELETE_ERROR_CLASS
#pragma weak mpix_delete_error_class_ = PMPIX_DELETE_ERROR_CLASS
#pragma weak mpix_delete_error_class = PMPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class__
#pragma weak mpix_delete_error_class__ = pmpix_delete_error_class__
#pragma weak mpix_delete_error_class_ = pmpix_delete_error_class__
#pragma weak mpix_delete_error_class = pmpix_delete_error_class__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class_
#pragma weak mpix_delete_error_class__ = pmpix_delete_error_class_
#pragma weak mpix_delete_error_class_ = pmpix_delete_error_class_
#pragma weak mpix_delete_error_class = pmpix_delete_error_class_
#else
#pragma weak MPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class
#pragma weak mpix_delete_error_class__ = pmpix_delete_error_class
#pragma weak mpix_delete_error_class_ = pmpix_delete_error_class
#pragma weak mpix_delete_error_class = pmpix_delete_error_class
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_DELETE_ERROR_CLASS = PMPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_delete_error_class__ = pmpix_delete_error_class__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_delete_error_class = pmpix_delete_error_class
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * );

#pragma weak mpix_delete_error_class_ = pmpix_delete_error_class_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_DELETE_ERROR_CLASS  MPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_delete_error_class__  mpix_delete_error_class__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_delete_error_class  mpix_delete_error_class
#else
#pragma _HP_SECONDARY_DEF pmpix_delete_error_class_  mpix_delete_error_class_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_DELETE_ERROR_CLASS as PMPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_delete_error_class__ as pmpix_delete_error_class__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_delete_error_class as pmpix_delete_error_class
#else
#pragma _CRI duplicate mpix_delete_error_class_ as pmpix_delete_error_class_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_delete_error_class__ = MPIX_DELETE_ERROR_CLASS
#pragma weak mpix_delete_error_class_ = MPIX_DELETE_ERROR_CLASS
#pragma weak mpix_delete_error_class = MPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_DELETE_ERROR_CLASS = mpix_delete_error_class__
#pragma weak mpix_delete_error_class_ = mpix_delete_error_class__
#pragma weak mpix_delete_error_class = mpix_delete_error_class__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_DELETE_ERROR_CLASS = mpix_delete_error_class_
#pragma weak mpix_delete_error_class__ = mpix_delete_error_class_
#pragma weak mpix_delete_error_class = mpix_delete_error_class_
#else
#pragma weak MPIX_DELETE_ERROR_CLASS = mpix_delete_error_class
#pragma weak mpix_delete_error_class__ = mpix_delete_error_class
#pragma weak mpix_delete_error_class_ = mpix_delete_error_class
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPIX_DELETE_ERROR_CLASS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class( MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class__( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class_( MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class( MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_delete_error_class__ = PMPIX_DELETE_ERROR_CLASS
#pragma weak pmpix_delete_error_class_ = PMPIX_DELETE_ERROR_CLASS
#pragma weak pmpix_delete_error_class = PMPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class__
#pragma weak pmpix_delete_error_class_ = pmpix_delete_error_class__
#pragma weak pmpix_delete_error_class = pmpix_delete_error_class__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class_
#pragma weak pmpix_delete_error_class__ = pmpix_delete_error_class_
#pragma weak pmpix_delete_error_class = pmpix_delete_error_class_
#else
#pragma weak PMPIX_DELETE_ERROR_CLASS = pmpix_delete_error_class
#pragma weak pmpix_delete_error_class__ = pmpix_delete_error_class
#pragma weak pmpix_delete_error_class_ = pmpix_delete_error_class
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPIX_DELETE_ERROR_CLASS")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPIX_DELETE_ERROR_CLASS( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class__( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_delete_error_class_( MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpix_delete_error_class")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpix_delete_error_class_ PMPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_delete_error_class_ pmpix_delete_error_class__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_delete_error_class_ pmpix_delete_error_class
#else
#define mpix_delete_error_class_ pmpix_delete_error_class_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Delete_error_class
#define MPIX_Delete_error_class PMPIX_Delete_error_class
#endif

#else

#ifdef F77_NAME_UPPER
#define mpix_delete_error_class_ MPIX_DELETE_ERROR_CLASS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_delete_error_class_ mpix_delete_error_class__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_delete_error_class_ mpix_delete_error_class
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_delete_error_class_ ( MPI_Fint *v1, MPI_Fint *ierr ){
    *ierr = MPIX_Delete_error_class( (int)*v1 );
}
