/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_ISENDRECV_REPLACE = PMPI_ISENDRECV_REPLACE
#pragma weak mpi_isendrecv_replace__ = PMPI_ISENDRECV_REPLACE
#pragma weak mpi_isendrecv_replace_ = PMPI_ISENDRECV_REPLACE
#pragma weak mpi_isendrecv_replace = PMPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace__
#pragma weak mpi_isendrecv_replace__ = pmpi_isendrecv_replace__
#pragma weak mpi_isendrecv_replace_ = pmpi_isendrecv_replace__
#pragma weak mpi_isendrecv_replace = pmpi_isendrecv_replace__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace_
#pragma weak mpi_isendrecv_replace__ = pmpi_isendrecv_replace_
#pragma weak mpi_isendrecv_replace_ = pmpi_isendrecv_replace_
#pragma weak mpi_isendrecv_replace = pmpi_isendrecv_replace_
#else
#pragma weak MPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace
#pragma weak mpi_isendrecv_replace__ = pmpi_isendrecv_replace
#pragma weak mpi_isendrecv_replace_ = pmpi_isendrecv_replace
#pragma weak mpi_isendrecv_replace = pmpi_isendrecv_replace
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_ISENDRECV_REPLACE = PMPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_isendrecv_replace__ = pmpi_isendrecv_replace__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_isendrecv_replace = pmpi_isendrecv_replace
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_isendrecv_replace_ = pmpi_isendrecv_replace_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_ISENDRECV_REPLACE  MPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_isendrecv_replace__  mpi_isendrecv_replace__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_isendrecv_replace  mpi_isendrecv_replace
#else
#pragma _HP_SECONDARY_DEF pmpi_isendrecv_replace_  mpi_isendrecv_replace_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_ISENDRECV_REPLACE as PMPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_isendrecv_replace__ as pmpi_isendrecv_replace__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_isendrecv_replace as pmpi_isendrecv_replace
#else
#pragma _CRI duplicate mpi_isendrecv_replace_ as pmpi_isendrecv_replace_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_isendrecv_replace__ = MPI_ISENDRECV_REPLACE
#pragma weak mpi_isendrecv_replace_ = MPI_ISENDRECV_REPLACE
#pragma weak mpi_isendrecv_replace = MPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_ISENDRECV_REPLACE = mpi_isendrecv_replace__
#pragma weak mpi_isendrecv_replace_ = mpi_isendrecv_replace__
#pragma weak mpi_isendrecv_replace = mpi_isendrecv_replace__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_ISENDRECV_REPLACE = mpi_isendrecv_replace_
#pragma weak mpi_isendrecv_replace__ = mpi_isendrecv_replace_
#pragma weak mpi_isendrecv_replace = mpi_isendrecv_replace_
#else
#pragma weak MPI_ISENDRECV_REPLACE = mpi_isendrecv_replace
#pragma weak mpi_isendrecv_replace__ = mpi_isendrecv_replace
#pragma weak mpi_isendrecv_replace_ = mpi_isendrecv_replace
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_ISENDRECV_REPLACE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_isendrecv_replace__ = PMPI_ISENDRECV_REPLACE
#pragma weak pmpi_isendrecv_replace_ = PMPI_ISENDRECV_REPLACE
#pragma weak pmpi_isendrecv_replace = PMPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace__
#pragma weak pmpi_isendrecv_replace_ = pmpi_isendrecv_replace__
#pragma weak pmpi_isendrecv_replace = pmpi_isendrecv_replace__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace_
#pragma weak pmpi_isendrecv_replace__ = pmpi_isendrecv_replace_
#pragma weak pmpi_isendrecv_replace = pmpi_isendrecv_replace_
#else
#pragma weak PMPI_ISENDRECV_REPLACE = pmpi_isendrecv_replace
#pragma weak pmpi_isendrecv_replace__ = pmpi_isendrecv_replace
#pragma weak pmpi_isendrecv_replace_ = pmpi_isendrecv_replace
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_ISENDRECV_REPLACE")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_ISENDRECV_REPLACE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_isendrecv_replace_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_isendrecv_replace")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_isendrecv_replace_ PMPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_isendrecv_replace_ pmpi_isendrecv_replace__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_isendrecv_replace_ pmpi_isendrecv_replace
#else
#define mpi_isendrecv_replace_ pmpi_isendrecv_replace_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Isendrecv_replace
#define MPI_Isendrecv_replace PMPI_Isendrecv_replace
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_isendrecv_replace_ MPI_ISENDRECV_REPLACE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_isendrecv_replace_ mpi_isendrecv_replace__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_isendrecv_replace_ mpi_isendrecv_replace
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_isendrecv_replace_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){
    if (v1 == MPIR_F_MPI_BOTTOM) v1 = MPI_BOTTOM;
    *ierr = MPI_Isendrecv_replace( v1, (int)*v2, (MPI_Datatype)(*v3), (int)*v4, (int)*v5, (int)*v6, (int)*v7, (MPI_Comm)(*v8), (MPI_Request *)(v9) );
}
