/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_PARRIVED = PMPI_PARRIVED
#pragma weak mpi_parrived__ = PMPI_PARRIVED
#pragma weak mpi_parrived_ = PMPI_PARRIVED
#pragma weak mpi_parrived = PMPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_PARRIVED = pmpi_parrived__
#pragma weak mpi_parrived__ = pmpi_parrived__
#pragma weak mpi_parrived_ = pmpi_parrived__
#pragma weak mpi_parrived = pmpi_parrived__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_PARRIVED = pmpi_parrived_
#pragma weak mpi_parrived__ = pmpi_parrived_
#pragma weak mpi_parrived_ = pmpi_parrived_
#pragma weak mpi_parrived = pmpi_parrived_
#else
#pragma weak MPI_PARRIVED = pmpi_parrived
#pragma weak mpi_parrived__ = pmpi_parrived
#pragma weak mpi_parrived_ = pmpi_parrived
#pragma weak mpi_parrived = pmpi_parrived
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_PARRIVED = PMPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_parrived__ = pmpi_parrived__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_parrived = pmpi_parrived
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_parrived_ = pmpi_parrived_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_PARRIVED  MPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_parrived__  mpi_parrived__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_parrived  mpi_parrived
#else
#pragma _HP_SECONDARY_DEF pmpi_parrived_  mpi_parrived_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_PARRIVED as PMPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_parrived__ as pmpi_parrived__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_parrived as pmpi_parrived
#else
#pragma _CRI duplicate mpi_parrived_ as pmpi_parrived_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_parrived__ = MPI_PARRIVED
#pragma weak mpi_parrived_ = MPI_PARRIVED
#pragma weak mpi_parrived = MPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_PARRIVED = mpi_parrived__
#pragma weak mpi_parrived_ = mpi_parrived__
#pragma weak mpi_parrived = mpi_parrived__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_PARRIVED = mpi_parrived_
#pragma weak mpi_parrived__ = mpi_parrived_
#pragma weak mpi_parrived = mpi_parrived_
#else
#pragma weak MPI_PARRIVED = mpi_parrived
#pragma weak mpi_parrived__ = mpi_parrived
#pragma weak mpi_parrived_ = mpi_parrived
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PARRIVED")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL mpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_parrived__ = PMPI_PARRIVED
#pragma weak pmpi_parrived_ = PMPI_PARRIVED
#pragma weak pmpi_parrived = PMPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_PARRIVED = pmpi_parrived__
#pragma weak pmpi_parrived_ = pmpi_parrived__
#pragma weak pmpi_parrived = pmpi_parrived__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_PARRIVED = pmpi_parrived_
#pragma weak pmpi_parrived__ = pmpi_parrived_
#pragma weak pmpi_parrived = pmpi_parrived_
#else
#pragma weak PMPI_PARRIVED = pmpi_parrived
#pragma weak pmpi_parrived__ = pmpi_parrived
#pragma weak pmpi_parrived_ = pmpi_parrived
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PARRIVED")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_PARRIVED( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_parrived_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_parrived")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_parrived_ PMPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_parrived_ pmpi_parrived__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_parrived_ pmpi_parrived
#else
#define mpi_parrived_ pmpi_parrived_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Parrived
#define MPI_Parrived PMPI_Parrived
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_parrived_ MPI_PARRIVED
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_parrived_ mpi_parrived__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_parrived_ mpi_parrived
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_parrived_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *ierr ){
    *ierr = MPI_Parrived( (MPI_Request)*v1, (int)*v2, v3 );
}
