/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_PREADY = PMPI_PREADY
#pragma weak mpi_pready__ = PMPI_PREADY
#pragma weak mpi_pready_ = PMPI_PREADY
#pragma weak mpi_pready = PMPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_PREADY = pmpi_pready__
#pragma weak mpi_pready__ = pmpi_pready__
#pragma weak mpi_pready_ = pmpi_pready__
#pragma weak mpi_pready = pmpi_pready__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_PREADY = pmpi_pready_
#pragma weak mpi_pready__ = pmpi_pready_
#pragma weak mpi_pready_ = pmpi_pready_
#pragma weak mpi_pready = pmpi_pready_
#else
#pragma weak MPI_PREADY = pmpi_pready
#pragma weak mpi_pready__ = pmpi_pready
#pragma weak mpi_pready_ = pmpi_pready
#pragma weak mpi_pready = pmpi_pready
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_PREADY = PMPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_pready__ = pmpi_pready__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_pready = pmpi_pready
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_pready_ = pmpi_pready_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_PREADY  MPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_pready__  mpi_pready__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_pready  mpi_pready
#else
#pragma _HP_SECONDARY_DEF pmpi_pready_  mpi_pready_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_PREADY as PMPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_pready__ as pmpi_pready__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_pready as pmpi_pready
#else
#pragma _CRI duplicate mpi_pready_ as pmpi_pready_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_pready__ = MPI_PREADY
#pragma weak mpi_pready_ = MPI_PREADY
#pragma weak mpi_pready = MPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_PREADY = mpi_pready__
#pragma weak mpi_pready_ = mpi_pready__
#pragma weak mpi_pready = mpi_pready__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_PREADY = mpi_pready_
#pragma weak mpi_pready__ = mpi_pready_
#pragma weak mpi_pready = mpi_pready_
#else
#pragma weak MPI_PREADY = mpi_pready
#pragma weak mpi_pready__ = mpi_pready
#pragma weak mpi_pready_ = mpi_pready
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_PREADY")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL mpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_pready__ = PMPI_PREADY
#pragma weak pmpi_pready_ = PMPI_PREADY
#pragma weak pmpi_pready = PMPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_PREADY = pmpi_pready__
#pragma weak pmpi_pready_ = pmpi_pready__
#pragma weak pmpi_pready = pmpi_pready__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_PREADY = pmpi_pready_
#pragma weak pmpi_pready__ = pmpi_pready_
#pragma weak pmpi_pready = pmpi_pready_
#else
#pragma weak PMPI_PREADY = pmpi_pready
#pragma weak pmpi_pready__ = pmpi_pready
#pragma weak pmpi_pready_ = pmpi_pready
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_PREADY")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_PREADY( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready__( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_pready_( MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_pready")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_pready_ PMPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_pready_ pmpi_pready__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_pready_ pmpi_pready
#else
#define mpi_pready_ pmpi_pready_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Pready
#define MPI_Pready PMPI_Pready
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_pready_ MPI_PREADY
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_pready_ mpi_pready__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_pready_ mpi_pready
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_pready_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *ierr ){
    *ierr = MPI_Pready( (int)*v1, (MPI_Request)*v2 );
}
