/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_REDUCE_INIT = PMPI_REDUCE_INIT
#pragma weak mpi_reduce_init__ = PMPI_REDUCE_INIT
#pragma weak mpi_reduce_init_ = PMPI_REDUCE_INIT
#pragma weak mpi_reduce_init = PMPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REDUCE_INIT = pmpi_reduce_init__
#pragma weak mpi_reduce_init__ = pmpi_reduce_init__
#pragma weak mpi_reduce_init_ = pmpi_reduce_init__
#pragma weak mpi_reduce_init = pmpi_reduce_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REDUCE_INIT = pmpi_reduce_init_
#pragma weak mpi_reduce_init__ = pmpi_reduce_init_
#pragma weak mpi_reduce_init_ = pmpi_reduce_init_
#pragma weak mpi_reduce_init = pmpi_reduce_init_
#else
#pragma weak MPI_REDUCE_INIT = pmpi_reduce_init
#pragma weak mpi_reduce_init__ = pmpi_reduce_init
#pragma weak mpi_reduce_init_ = pmpi_reduce_init
#pragma weak mpi_reduce_init = pmpi_reduce_init
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_REDUCE_INIT = PMPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_init__ = pmpi_reduce_init__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_init = pmpi_reduce_init
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_init_ = pmpi_reduce_init_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_REDUCE_INIT  MPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_reduce_init__  mpi_reduce_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_reduce_init  mpi_reduce_init
#else
#pragma _HP_SECONDARY_DEF pmpi_reduce_init_  mpi_reduce_init_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_REDUCE_INIT as PMPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_reduce_init__ as pmpi_reduce_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_reduce_init as pmpi_reduce_init
#else
#pragma _CRI duplicate mpi_reduce_init_ as pmpi_reduce_init_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_reduce_init__ = MPI_REDUCE_INIT
#pragma weak mpi_reduce_init_ = MPI_REDUCE_INIT
#pragma weak mpi_reduce_init = MPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REDUCE_INIT = mpi_reduce_init__
#pragma weak mpi_reduce_init_ = mpi_reduce_init__
#pragma weak mpi_reduce_init = mpi_reduce_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REDUCE_INIT = mpi_reduce_init_
#pragma weak mpi_reduce_init__ = mpi_reduce_init_
#pragma weak mpi_reduce_init = mpi_reduce_init_
#else
#pragma weak MPI_REDUCE_INIT = mpi_reduce_init
#pragma weak mpi_reduce_init__ = mpi_reduce_init
#pragma weak mpi_reduce_init_ = mpi_reduce_init
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_REDUCE_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_reduce_init__ = PMPI_REDUCE_INIT
#pragma weak pmpi_reduce_init_ = PMPI_REDUCE_INIT
#pragma weak pmpi_reduce_init = PMPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_REDUCE_INIT = pmpi_reduce_init__
#pragma weak pmpi_reduce_init_ = pmpi_reduce_init__
#pragma weak pmpi_reduce_init = pmpi_reduce_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_REDUCE_INIT = pmpi_reduce_init_
#pragma weak pmpi_reduce_init__ = pmpi_reduce_init_
#pragma weak pmpi_reduce_init = pmpi_reduce_init_
#else
#pragma weak PMPI_REDUCE_INIT = pmpi_reduce_init
#pragma weak pmpi_reduce_init__ = pmpi_reduce_init
#pragma weak pmpi_reduce_init_ = pmpi_reduce_init
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_REDUCE_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_REDUCE_INIT( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_init_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_reduce_init")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_reduce_init_ PMPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_reduce_init_ pmpi_reduce_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_reduce_init_ pmpi_reduce_init
#else
#define mpi_reduce_init_ pmpi_reduce_init_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Reduce_init
#define MPI_Reduce_init PMPI_Reduce_init
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_reduce_init_ MPI_REDUCE_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_reduce_init_ mpi_reduce_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_reduce_init_ mpi_reduce_init
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_reduce_init_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){
    if (v1 == MPIR_F_MPI_BOTTOM) v1 = MPI_BOTTOM;
    if (v2 == MPIR_F_MPI_BOTTOM) v2 = MPI_BOTTOM;
    *ierr = MPI_Reduce_init( v1, v2, (int)*v3, (MPI_Datatype)(*v4), (MPI_Op)*v5, (int)*v6, (MPI_Comm)(*v7), (MPI_Info)(*v8), (MPI_Request *)(v9) );
}
