/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_REGISTER_DATAREP_C = PMPI_REGISTER_DATAREP_C
#pragma weak mpi_register_datarep_c__ = PMPI_REGISTER_DATAREP_C
#pragma weak mpi_register_datarep_c_ = PMPI_REGISTER_DATAREP_C
#pragma weak mpi_register_datarep_c = PMPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REGISTER_DATAREP_C = pmpi_register_datarep_c__
#pragma weak mpi_register_datarep_c__ = pmpi_register_datarep_c__
#pragma weak mpi_register_datarep_c_ = pmpi_register_datarep_c__
#pragma weak mpi_register_datarep_c = pmpi_register_datarep_c__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REGISTER_DATAREP_C = pmpi_register_datarep_c_
#pragma weak mpi_register_datarep_c__ = pmpi_register_datarep_c_
#pragma weak mpi_register_datarep_c_ = pmpi_register_datarep_c_
#pragma weak mpi_register_datarep_c = pmpi_register_datarep_c_
#else
#pragma weak MPI_REGISTER_DATAREP_C = pmpi_register_datarep_c
#pragma weak mpi_register_datarep_c__ = pmpi_register_datarep_c
#pragma weak mpi_register_datarep_c_ = pmpi_register_datarep_c
#pragma weak mpi_register_datarep_c = pmpi_register_datarep_c
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak MPI_REGISTER_DATAREP_C = PMPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_register_datarep_c__ = pmpi_register_datarep_c__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_register_datarep_c = pmpi_register_datarep_c
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_register_datarep_c_ = pmpi_register_datarep_c_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_REGISTER_DATAREP_C  MPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_register_datarep_c__  mpi_register_datarep_c__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_register_datarep_c  mpi_register_datarep_c
#else
#pragma _HP_SECONDARY_DEF pmpi_register_datarep_c_  mpi_register_datarep_c_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_REGISTER_DATAREP_C as PMPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_register_datarep_c__ as pmpi_register_datarep_c__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_register_datarep_c as pmpi_register_datarep_c
#else
#pragma _CRI duplicate mpi_register_datarep_c_ as pmpi_register_datarep_c_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_register_datarep_c__ = MPI_REGISTER_DATAREP_C
#pragma weak mpi_register_datarep_c_ = MPI_REGISTER_DATAREP_C
#pragma weak mpi_register_datarep_c = MPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REGISTER_DATAREP_C = mpi_register_datarep_c__
#pragma weak mpi_register_datarep_c_ = mpi_register_datarep_c__
#pragma weak mpi_register_datarep_c = mpi_register_datarep_c__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REGISTER_DATAREP_C = mpi_register_datarep_c_
#pragma weak mpi_register_datarep_c__ = mpi_register_datarep_c_
#pragma weak mpi_register_datarep_c = mpi_register_datarep_c_
#else
#pragma weak MPI_REGISTER_DATAREP_C = mpi_register_datarep_c
#pragma weak mpi_register_datarep_c__ = mpi_register_datarep_c
#pragma weak mpi_register_datarep_c_ = mpi_register_datarep_c
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_REGISTER_DATAREP_C")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_register_datarep_c__ = PMPI_REGISTER_DATAREP_C
#pragma weak pmpi_register_datarep_c_ = PMPI_REGISTER_DATAREP_C
#pragma weak pmpi_register_datarep_c = PMPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_REGISTER_DATAREP_C = pmpi_register_datarep_c__
#pragma weak pmpi_register_datarep_c_ = pmpi_register_datarep_c__
#pragma weak pmpi_register_datarep_c = pmpi_register_datarep_c__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_REGISTER_DATAREP_C = pmpi_register_datarep_c_
#pragma weak pmpi_register_datarep_c__ = pmpi_register_datarep_c_
#pragma weak pmpi_register_datarep_c = pmpi_register_datarep_c_
#else
#pragma weak PMPI_REGISTER_DATAREP_C = pmpi_register_datarep_c
#pragma weak pmpi_register_datarep_c__ = pmpi_register_datarep_c
#pragma weak pmpi_register_datarep_c_ = pmpi_register_datarep_c
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_REGISTER_DATAREP_C")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_REGISTER_DATAREP_C( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c__( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_register_datarep_c_( char * FORT_MIXED_LEN_DECL, MPI_Datarep_conversion_function_c*, MPI_Datarep_conversion_function_c*, MPI_Datarep_extent_function*, void*, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_register_datarep_c")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_register_datarep_c_ PMPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_register_datarep_c_ pmpi_register_datarep_c__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_register_datarep_c_ pmpi_register_datarep_c
#else
#define mpi_register_datarep_c_ pmpi_register_datarep_c_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Register_datarep_c
#define MPI_Register_datarep_c PMPI_Register_datarep_c
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_register_datarep_c_ MPI_REGISTER_DATAREP_C
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_register_datarep_c_ mpi_register_datarep_c__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_register_datarep_c_ mpi_register_datarep_c
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_register_datarep_c_ ( char *v1 FORT_MIXED_LEN(d1), MPI_Datarep_conversion_function_c*v2, MPI_Datarep_conversion_function_c*v3, MPI_Datarep_extent_function*v4, void*v5, MPI_Fint *ierr FORT_END_LEN(d1) ){
#ifdef MPI_MODE_RDONLY
    if (v5 == MPIR_F_MPI_BOTTOM) v5 = MPI_BOTTOM;
    *ierr = MPI_Register_datarep_c( v1, v2, v3, v4, v5 );
#else
*ierr = MPI_ERR_INTERN;
#endif
}
