/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_SCATTERV_INIT = PMPI_SCATTERV_INIT
#pragma weak mpi_scatterv_init__ = PMPI_SCATTERV_INIT
#pragma weak mpi_scatterv_init_ = PMPI_SCATTERV_INIT
#pragma weak mpi_scatterv_init = PMPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SCATTERV_INIT = pmpi_scatterv_init__
#pragma weak mpi_scatterv_init__ = pmpi_scatterv_init__
#pragma weak mpi_scatterv_init_ = pmpi_scatterv_init__
#pragma weak mpi_scatterv_init = pmpi_scatterv_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SCATTERV_INIT = pmpi_scatterv_init_
#pragma weak mpi_scatterv_init__ = pmpi_scatterv_init_
#pragma weak mpi_scatterv_init_ = pmpi_scatterv_init_
#pragma weak mpi_scatterv_init = pmpi_scatterv_init_
#else
#pragma weak MPI_SCATTERV_INIT = pmpi_scatterv_init
#pragma weak mpi_scatterv_init__ = pmpi_scatterv_init
#pragma weak mpi_scatterv_init_ = pmpi_scatterv_init
#pragma weak mpi_scatterv_init = pmpi_scatterv_init
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_SCATTERV_INIT = PMPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_scatterv_init__ = pmpi_scatterv_init__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_scatterv_init = pmpi_scatterv_init
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_scatterv_init_ = pmpi_scatterv_init_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_SCATTERV_INIT  MPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_scatterv_init__  mpi_scatterv_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_scatterv_init  mpi_scatterv_init
#else
#pragma _HP_SECONDARY_DEF pmpi_scatterv_init_  mpi_scatterv_init_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_SCATTERV_INIT as PMPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_scatterv_init__ as pmpi_scatterv_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_scatterv_init as pmpi_scatterv_init
#else
#pragma _CRI duplicate mpi_scatterv_init_ as pmpi_scatterv_init_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_scatterv_init__ = MPI_SCATTERV_INIT
#pragma weak mpi_scatterv_init_ = MPI_SCATTERV_INIT
#pragma weak mpi_scatterv_init = MPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SCATTERV_INIT = mpi_scatterv_init__
#pragma weak mpi_scatterv_init_ = mpi_scatterv_init__
#pragma weak mpi_scatterv_init = mpi_scatterv_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SCATTERV_INIT = mpi_scatterv_init_
#pragma weak mpi_scatterv_init__ = mpi_scatterv_init_
#pragma weak mpi_scatterv_init = mpi_scatterv_init_
#else
#pragma weak MPI_SCATTERV_INIT = mpi_scatterv_init
#pragma weak mpi_scatterv_init__ = mpi_scatterv_init
#pragma weak mpi_scatterv_init_ = mpi_scatterv_init
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("MPI_SCATTERV_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("mpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_scatterv_init__ = PMPI_SCATTERV_INIT
#pragma weak pmpi_scatterv_init_ = PMPI_SCATTERV_INIT
#pragma weak pmpi_scatterv_init = PMPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_SCATTERV_INIT = pmpi_scatterv_init__
#pragma weak pmpi_scatterv_init_ = pmpi_scatterv_init__
#pragma weak pmpi_scatterv_init = pmpi_scatterv_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_SCATTERV_INIT = pmpi_scatterv_init_
#pragma weak pmpi_scatterv_init__ = pmpi_scatterv_init_
#pragma weak pmpi_scatterv_init = pmpi_scatterv_init_
#else
#pragma weak PMPI_SCATTERV_INIT = pmpi_scatterv_init
#pragma weak pmpi_scatterv_init__ = pmpi_scatterv_init
#pragma weak pmpi_scatterv_init_ = pmpi_scatterv_init
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("PMPI_SCATTERV_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_SCATTERV_INIT( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_scatterv_init_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * ) __attribute__((weak,alias("pmpi_scatterv_init")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_scatterv_init_ PMPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_scatterv_init_ pmpi_scatterv_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_scatterv_init_ pmpi_scatterv_init
#else
#define mpi_scatterv_init_ pmpi_scatterv_init_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Scatterv_init
#define MPI_Scatterv_init PMPI_Scatterv_init
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_scatterv_init_ MPI_SCATTERV_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_scatterv_init_ mpi_scatterv_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_scatterv_init_ mpi_scatterv_init
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_scatterv_init_ ( void*v1, MPI_Fint v2[], MPI_Fint v3[], MPI_Fint *v4, void*v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *v11, MPI_Fint *ierr ){
    if (v1 == MPIR_F_MPI_BOTTOM) v1 = MPI_BOTTOM;
    if (v5 == MPIR_F_MPI_BOTTOM) v5 = MPI_BOTTOM;
    *ierr = MPI_Scatterv_init( v1, v2, v3, (MPI_Datatype)(*v4), v5, (int)*v6, (MPI_Datatype)(*v7), (int)*v8, (MPI_Comm)(*v9), (MPI_Info)(*v10), (MPI_Request *)(v11) );
}
