/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_SESSION_GET_NTH_PSET = PMPI_SESSION_GET_NTH_PSET
#pragma weak mpi_session_get_nth_pset__ = PMPI_SESSION_GET_NTH_PSET
#pragma weak mpi_session_get_nth_pset_ = PMPI_SESSION_GET_NTH_PSET
#pragma weak mpi_session_get_nth_pset = PMPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset__
#pragma weak mpi_session_get_nth_pset__ = pmpi_session_get_nth_pset__
#pragma weak mpi_session_get_nth_pset_ = pmpi_session_get_nth_pset__
#pragma weak mpi_session_get_nth_pset = pmpi_session_get_nth_pset__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset_
#pragma weak mpi_session_get_nth_pset__ = pmpi_session_get_nth_pset_
#pragma weak mpi_session_get_nth_pset_ = pmpi_session_get_nth_pset_
#pragma weak mpi_session_get_nth_pset = pmpi_session_get_nth_pset_
#else
#pragma weak MPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset
#pragma weak mpi_session_get_nth_pset__ = pmpi_session_get_nth_pset
#pragma weak mpi_session_get_nth_pset_ = pmpi_session_get_nth_pset
#pragma weak mpi_session_get_nth_pset = pmpi_session_get_nth_pset
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak MPI_SESSION_GET_NTH_PSET = PMPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_session_get_nth_pset__ = pmpi_session_get_nth_pset__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_session_get_nth_pset = pmpi_session_get_nth_pset
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#pragma weak mpi_session_get_nth_pset_ = pmpi_session_get_nth_pset_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_SESSION_GET_NTH_PSET  MPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_session_get_nth_pset__  mpi_session_get_nth_pset__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_session_get_nth_pset  mpi_session_get_nth_pset
#else
#pragma _HP_SECONDARY_DEF pmpi_session_get_nth_pset_  mpi_session_get_nth_pset_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_SESSION_GET_NTH_PSET as PMPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_session_get_nth_pset__ as pmpi_session_get_nth_pset__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_session_get_nth_pset as pmpi_session_get_nth_pset
#else
#pragma _CRI duplicate mpi_session_get_nth_pset_ as pmpi_session_get_nth_pset_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_session_get_nth_pset__ = MPI_SESSION_GET_NTH_PSET
#pragma weak mpi_session_get_nth_pset_ = MPI_SESSION_GET_NTH_PSET
#pragma weak mpi_session_get_nth_pset = MPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SESSION_GET_NTH_PSET = mpi_session_get_nth_pset__
#pragma weak mpi_session_get_nth_pset_ = mpi_session_get_nth_pset__
#pragma weak mpi_session_get_nth_pset = mpi_session_get_nth_pset__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SESSION_GET_NTH_PSET = mpi_session_get_nth_pset_
#pragma weak mpi_session_get_nth_pset__ = mpi_session_get_nth_pset_
#pragma weak mpi_session_get_nth_pset = mpi_session_get_nth_pset_
#else
#pragma weak MPI_SESSION_GET_NTH_PSET = mpi_session_get_nth_pset
#pragma weak mpi_session_get_nth_pset__ = mpi_session_get_nth_pset
#pragma weak mpi_session_get_nth_pset_ = mpi_session_get_nth_pset
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("MPI_SESSION_GET_NTH_PSET")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("mpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_session_get_nth_pset__ = PMPI_SESSION_GET_NTH_PSET
#pragma weak pmpi_session_get_nth_pset_ = PMPI_SESSION_GET_NTH_PSET
#pragma weak pmpi_session_get_nth_pset = PMPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset__
#pragma weak pmpi_session_get_nth_pset_ = pmpi_session_get_nth_pset__
#pragma weak pmpi_session_get_nth_pset = pmpi_session_get_nth_pset__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset_
#pragma weak pmpi_session_get_nth_pset__ = pmpi_session_get_nth_pset_
#pragma weak pmpi_session_get_nth_pset = pmpi_session_get_nth_pset_
#else
#pragma weak PMPI_SESSION_GET_NTH_PSET = pmpi_session_get_nth_pset
#pragma weak pmpi_session_get_nth_pset__ = pmpi_session_get_nth_pset
#pragma weak pmpi_session_get_nth_pset_ = pmpi_session_get_nth_pset
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("PMPI_SESSION_GET_NTH_PSET")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_GET_NTH_PSET( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset__( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_get_nth_pset_( MPI_Session, MPI_Fint *, MPI_Fint *, MPI_Fint *, char * FORT_MIXED_LEN_DECL, MPI_Fint * FORT_END_LEN_DECL ) __attribute__((weak,alias("pmpi_session_get_nth_pset")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_session_get_nth_pset_ PMPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_session_get_nth_pset_ pmpi_session_get_nth_pset__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_session_get_nth_pset_ pmpi_session_get_nth_pset
#else
#define mpi_session_get_nth_pset_ pmpi_session_get_nth_pset_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Session_get_nth_pset
#define MPI_Session_get_nth_pset PMPI_Session_get_nth_pset
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_session_get_nth_pset_ MPI_SESSION_GET_NTH_PSET
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_session_get_nth_pset_ mpi_session_get_nth_pset__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_session_get_nth_pset_ mpi_session_get_nth_pset
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_session_get_nth_pset_ ( MPI_Session v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, char *v5 FORT_MIXED_LEN(d5), MPI_Fint *ierr FORT_END_LEN(d5) ){
    *ierr = MPI_Session_get_nth_pset( v1, (MPI_Info)(*v2), (int)*v3, v4, v5 );
}
