/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_SESSION_INIT = PMPI_SESSION_INIT
#pragma weak mpi_session_init__ = PMPI_SESSION_INIT
#pragma weak mpi_session_init_ = PMPI_SESSION_INIT
#pragma weak mpi_session_init = PMPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SESSION_INIT = pmpi_session_init__
#pragma weak mpi_session_init__ = pmpi_session_init__
#pragma weak mpi_session_init_ = pmpi_session_init__
#pragma weak mpi_session_init = pmpi_session_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SESSION_INIT = pmpi_session_init_
#pragma weak mpi_session_init__ = pmpi_session_init_
#pragma weak mpi_session_init_ = pmpi_session_init_
#pragma weak mpi_session_init = pmpi_session_init_
#else
#pragma weak MPI_SESSION_INIT = pmpi_session_init
#pragma weak mpi_session_init__ = pmpi_session_init
#pragma weak mpi_session_init_ = pmpi_session_init
#pragma weak mpi_session_init = pmpi_session_init
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#pragma weak MPI_SESSION_INIT = PMPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#pragma weak mpi_session_init__ = pmpi_session_init__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#pragma weak mpi_session_init = pmpi_session_init
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#pragma weak mpi_session_init_ = pmpi_session_init_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_SESSION_INIT  MPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_session_init__  mpi_session_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_session_init  mpi_session_init
#else
#pragma _HP_SECONDARY_DEF pmpi_session_init_  mpi_session_init_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_SESSION_INIT as PMPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_session_init__ as pmpi_session_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_session_init as pmpi_session_init
#else
#pragma _CRI duplicate mpi_session_init_ as pmpi_session_init_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_session_init__ = MPI_SESSION_INIT
#pragma weak mpi_session_init_ = MPI_SESSION_INIT
#pragma weak mpi_session_init = MPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_SESSION_INIT = mpi_session_init__
#pragma weak mpi_session_init_ = mpi_session_init__
#pragma weak mpi_session_init = mpi_session_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_SESSION_INIT = mpi_session_init_
#pragma weak mpi_session_init__ = mpi_session_init_
#pragma weak mpi_session_init = mpi_session_init_
#else
#pragma weak MPI_SESSION_INIT = mpi_session_init
#pragma weak mpi_session_init__ = mpi_session_init
#pragma weak mpi_session_init_ = mpi_session_init
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("MPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("MPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("MPI_SESSION_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("mpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL mpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_session_init__ = PMPI_SESSION_INIT
#pragma weak pmpi_session_init_ = PMPI_SESSION_INIT
#pragma weak pmpi_session_init = PMPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_SESSION_INIT = pmpi_session_init__
#pragma weak pmpi_session_init_ = pmpi_session_init__
#pragma weak pmpi_session_init = pmpi_session_init__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_SESSION_INIT = pmpi_session_init_
#pragma weak pmpi_session_init__ = pmpi_session_init_
#pragma weak pmpi_session_init = pmpi_session_init_
#else
#pragma weak PMPI_SESSION_INIT = pmpi_session_init
#pragma weak pmpi_session_init__ = pmpi_session_init
#pragma weak pmpi_session_init_ = pmpi_session_init
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("PMPI_SESSION_INIT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPI_SESSION_INIT( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init__( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));
extern FORT_DLL_SPEC void FORT_CALL pmpi_session_init_( MPI_Fint *, MPI_Fint *, MPI_Session*, MPI_Fint * ) __attribute__((weak,alias("pmpi_session_init")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpi_session_init_ PMPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_session_init_ pmpi_session_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_session_init_ pmpi_session_init
#else
#define mpi_session_init_ pmpi_session_init_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPI_Session_init
#define MPI_Session_init PMPI_Session_init
#endif

#else

#ifdef F77_NAME_UPPER
#define mpi_session_init_ MPI_SESSION_INIT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_session_init_ mpi_session_init__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_session_init_ mpi_session_init
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_session_init_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Session*v3, MPI_Fint *ierr ){
    *ierr = MPI_Session_init( (MPI_Info)(*v1), (MPI_Errhandler)*v2, v3 );
}
