#! /bin/sh
# When configured within MPICH via PAC_CONFIG_SUBDIR, this file will be sourced
# by the top-level configure.  This lets us propagate shell variable changes
# back upstream.

GPU_SUPPORT=""
CPPFLAGS="-DNETMOD_INLINE=__netmod_inline_ofi__ -D__HIP_PLATFORM_AMD__ -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/src/mpl/include -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/modules/json-c -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/modules/hwloc/include -D_REENTRANT -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/src/mpi/romio/include -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/modules/libfabric/include -I/global/homes/k/keeganih/pmio-slimmed/code/mpi-tmpfs-log/modules/yaksa/src/frontend/include -D__HIP_PLATFORM_AMD__"
WRAPPER_LIBS="$WRAPPER_LIBS -lpthread "
